version: '3.8'
services:
  empleado:
    image: 'mysql'
    restart: always
    environment:
      - MYSQL_DATABASE=empleado
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 33060:3306

  empleado-service:
    image: 'johnserrano159/empleado-service'
    restart: always
    container_name: empleado-service
    environment:
      - spring.cloud.config.uri=http://config-service:8081
      - spring.config.import=optional:configserver:http://config-service:8081
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://empleado:3306/empleado?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA=eureka-service
    ports:
      - 8082:8082
    depends_on:
      - empleado

  marcas-reloj:
    image: 'mysql'
    restart: always
    environment:
      - MYSQL_DATABASE=marcasreloj
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 33061:3306
  
  marcas-reloj-service:
    image: 'johnserrano159/marcas-reloj-service'
    restart: always
    container_name: marcas-reloj-service
    environment:
      - spring.cloud.config.uri=http://config-service:8081
      - spring.config.import=optional:configserver:http://config-service:8081
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://marcas-reloj:3306/marcasreloj?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA=eureka-service
    ports:
      - 8083:8083
    depends_on:
      - marcas-reloj

  autorizacion:
    image: 'mysql'
    restart: always
    environment:
      - MYSQL_DATABASE=autorizacion
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 33062:3306
  
  autorizacion-service:
    image: 'johnserrano159/autorizacion-service'
    restart: always
    container_name: autorizacion-service
    environment:
      - spring.cloud.config.uri=http://config-service:8081
      - spring.config.import=optional:configserver:http://config-service:8081
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://autorizacion:3306/autorizacion?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA=eureka-service
    ports:
      - 8084:8084
    depends_on:
      - autorizacion
    
  justificativo:
    image: 'mysql'
    restart: always
    environment:
      - MYSQL_DATABASE=justificativo
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 33063:3306
  
  justificativo-service:
    image: 'johnserrano159/justificativo-service'
    restart: always
    container_name: justificativo-service
    environment:
      - spring.cloud.config.uri=http://config-service:8081
      - spring.config.import=optional:configserver:http://config-service:8081
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://justificativo:3306/justificativo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA=eureka-service
    ports:
      - 8086:8086
    depends_on:
      - justificativo

  oficinarrhh:
    image: 'mysql'
    restart: always
    environment:
      - MYSQL_DATABASE=oficinarrhh
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 33064:3306
  
  oficinarrhh-service:
    image: 'johnserrano159/oficinarrhh-service'
    restart: always
    container_name: oficinarrhh-service
    environment:
      - spring.cloud.config.uri=http://config-service:8081
      - spring.config.import=optional:configserver:http://config-service:8081
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://oficinarrhh:3306/oficinarrhh?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA=eureka-service
    ports:
      - 8087:8087
    depends_on:
      - oficinarrhh
      - empleado-service
      - marcas-reloj-service
      - autorizacion-service
      - justificativo-service

  gateway-service:
    container_name: gateway-service
    image: johnserrano159/gateway-service:latest
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - empleado-service
      - marcas-reloj-service
      - autorizacion-service
      - justificativo-service
      - oficinarrhh-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka
      - spring.cloud.config.uri=http://config-service:8081
      - spring.config.import=optional:configserver:http://config-service:8081
      - EUREKA=eureka-service

  frontend-mueblesstgo:
    container_name: frontend-mueblesstgo
    image: johnserrano159/frontend-mueblsstgo:latest
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - empleado-service
      - marcas-reloj-service
      - autorizacion-service
      - justificativo-service
      - oficinarrhh-service
      - gateway-service
    deploy:
      restart_policy:
        condition: on-failure

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:20.0.1
    command: ["start-dev", "--http-port=8085"]
    ports:
      - "8085:8085"
    environment:
      - KEYCLOAK_USER=administrador
      - KEYCLOAK_PASSWORD=admin123
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin