version: '3.8'
services:
  config-service:
    image: 'johnserrano159/config-service'
    restart: always
    container_name: config-service
    ports:
      - 8081:8081
  eureka-service:
    image: 'johnserrano159/eureka-service'
    restart: always
    container_name: eureka-service
    depends_on:
      - config-service
    environment:
      - spring.cloud.config.uri=http://config-service:8081
      - spring.config.import=optional:configserver:http://config-service:8081
    ports:
      - 8761:8761
    hostname: eureka-service